services:
  fastapi-app:
    container_name: fastapi-chaos-app
    image: qiross/fastapi-chaos:latest
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"